#!/usr/bin/env python3
"""Add localized tips/name/description fields to seed_data.json for es, de, ru, zh.
Spanish (es) and German (de) are populated; Russian and Chinese left empty (fallback to English).
"""

import json, re

SEED = "/Users/usuario/Code/mallorca-explorer/app/src/main/assets/seed_data.json"

# ── Spanish tips translations ──────────────────────────────────────────────────
TIPS_ES = {
    "es-trenc": ["Llega antes de las 10h en verano", "Zona naturista en el extremo occidental", "El aparcamiento se llena rápido — toma el autobús desde Campos"],
    "cala-mondrag": ["Forma parte de un parque natural protegido", "Camina entre las dos calas", "Excelente snorkel entre las rocas"],
    "formentor-beach": ["Acceso en barco desde Port de Pollença en temporada alta", "Llega temprano — el aparcamiento es limitado", "El recorrido por el Cap de Formentor es espectacular"],
    "cala-deia": ["10 minutos a pie bajando desde el pueblo de Deià", "Reserva mesa en el Restaurante Ca's Patro March para marisco", "Orilla rocosa — se recomiendan escarpines"],
    "cala-pi": ["Estrecha entrada en forma de fiordo, perfecta para niños", "Sube al mirador de la torre para vistas panorámicas", "Aparcamiento limitado en temporada alta"],
    "cala-varques": ["Solo accesible a pie — unos 20 minutos desde la carretera", "Lleva agua y comida, no hay servicios", "Snorkel excepcional en sus aguas cristalinas"],
    "tramuntana-range": ["La Serra está declarada Patrimonio Mundial de la UNESCO desde 2011", "El mirador de Ses Barques ofrece las mejores vistas", "La ruta más popular es el Camí de s'Arxiduc"],
    "barranc-biniaraix": ["Empieza en el pueblo de Biniaraix, a las afueras de Sóller", "Los adoquines históricos pueden estar resbaladizos cuando está mojado", "Lleva calzado de senderismo robusto"],
    "puig-major": ["La cima está restringida por instalaciones militares", "Las mejores vistas son desde el mirador junto a la carretera", "El embalse de Cúber a sus pies es muy fotogénico"],
    "sa-calobra": ["La carretera en espiral con 270° es emblemática", "Llega en ferry desde Sóller para evitar atascos", "El torrente al lado de la playa conduce a una cala oculta"],
    "seu-cathedral": ["Visita al atardecer para ver la luz filtrarse por las vidrieras", "Los andamios de Gaudí son parte permanente del interior", "La vista desde el Parque del Mar al amanecer es impresionante"],
    "bellver-castle": ["La vista sobre la bahía de Palma es impresionante", "Los conciertos de verano en el castillo son muy populares", "El bosque circundante es ideal para pasear"],
    "fundacio-miro": ["El estudio de Miró fue preservado tal como lo dejó", "La tienda tiene reproducciones únicas no disponibles en otros museos", "La terraza con vistas al mar merece la pena"],
    "es-baluard": ["La terraza del museo ofrece vistas increíbles sobre Palma", "Entrada gratuita los viernes por la tarde", "La integración del museo con las murallas históricas es única"],
    "valldemossa": ["Visita la celda donde Chopin y George Sand pasaron el invierno de 1838-39", "La Real Cartuja está abierta al público la mayor parte del año", "El mercado de los domingos es encantador"],
    "deia": ["La cala de Deià es una pequeña joya rocosa a 10 minutos a pie", "En verano las terrazas requieren reserva con antelación", "El cementerio con vistas al mar es uno de los más hermosos de Europa"],
    "soller": ["El tranvía histórico conecta el pueblo con el Puerto de Sóller", "El tren de madera desde Palma tarda 1 hora y vale la pena", "El mercado del sábado es el más auténtico del valle"],
    "pollenca": ["Los 365 escalones del Calvario llevan a una iglesia con vistas espectaculares", "El mercado del domingo alrededor del claustro es imprescindible", "La Font de Sant Jordi es ideal para familias"],
    "cap-formentor": ["La carretera puede cerrarse en verano — comprueba las restricciones", "Llega al faro antes de las 9h para evitar aglomeraciones", "Los vencejos que anidan en los acantilados son fascinantes"],
    "mirador-ses-barques": ["Parada obligatoria en la carretera de Sóller al Port", "El café del mirador sirve los mejores ensaimadas del área", "Mejor al atardecer cuando la luz ilumina el puerto"],
    "restaurant-mola": ["Reserva con meses de antelación para el menú degustación", "El chef Joan Mora trabaja con productores locales de Mallorca", "El maridaje de vinos mallorquines es excepcional"],
    "restaurant-juanito": ["Famoso por sus croquetas caseras y el pan con sobrasada", "Solo efectivo — lleva moneda local", "Llega pronto ya que la cola se forma rápidamente"],
    "mercat-santa-catalina": ["El mercado está abierto de lunes a sábado por la mañana", "Los bares alrededor sirven desayunos mallorquines auténticos", "El barrio tiene la mejor oferta gastronómica de Palma"],
    "bodega-trevin": ["Las visitas incluyen cata de vino y aceite de oliva mallorquín", "El Manto Negro es la variedad tinta más representativa de Mallorca", "Llama con antelación para reservar visita guiada"],
    "coves-drach": ["Las visitas están programadas con horarios fijos, compra entradas online", "El concierto de música clásica en el lago subterráneo es espectacular", "La temperatura interior es de 21°C — lleva una capa"],
    "kayak-soller": ["Las excursiones al atardecer son las más populares — reserva con días de antelación", "Se requiere cierto nivel de forma física para las rutas más largas", "El snorkel incluido muestra cuevas y fondos marinos espectaculares"],
    "cami-des-correu": ["El sendero conecta varias localidades históricas de la costa", "Lleva mapa descargado ya que la señalización puede fallar", "La mejor época es primavera y otoño para evitar el calor"],
    "castell-alaro": ["La subida desde Alaró tarda aproximadamente 2 horas", "El refugio en la cima sirve comida casera simple", "Las vistas son 360°, perfectas para orientarse en Mallorca"],
    "puig-ofre": ["Ruta circular desde el Barranc de Biniaraix", "El sendero GR221 pasa por la cima", "Las plantas endémicas de la Tramuntana son visibles en primavera"],
    "puig-tomir": ["Punto de partida en el Coll de Sa Bataia", "Es una ruta de montaña real — lleva equipo adecuado", "Desde la cima se ven tanto la bahía de Pollença como la de Alcúdia"],
    "cami-arxiduc": ["La ruta empieza en Valldemossa o Son Gual", "Las partes de cresta pueden ser vertiginosas — no recomendado para vértigo", "El Arxiduc Luis Salvador construyó este sendero para explorar sus tierras"],
    "cala-tuent": ["La carretera de acceso es estrecha y con curvas pronunciadas", "Las familias prefieren Sa Calobra que está muy cerca", "Los pinos hasta la orilla crean una sombra perfecta"],
    "torrent-pareis": ["El descenso por el barranco requiere experiencia de cañoning", "En temporada de lluvias puede ser peligroso — consulta el tiempo antes", "La llegada al mar entre los acantilados es espectacular"],
    "cala-marmols": ["Solo accesible a pie desde Es Carbó o en barco", "Una de las pocas playas vírgenes que quedan en el sur de Mallorca", "El agua es extraordinariamente clara para snorkel"],
    "monestir-lluc": ["El Monasterio es el corazón espiritual de Mallorca", "Los niños cantores de la Escolanía actúan regularmente — consulta horarios", "El camino de ronda alrededor del monasterio tiene vistas preciosas"],
    "faro-formentor": ["La carretera puede estar cerrada a vehículos privados en temporada alta", "El servicio de autobús desde Pollença es la opción más cómoda", "Los delfines son avistados frecuentemente desde el faro"],
    "sa-foradada": ["El camino desde Son Marroig tarda unos 30 minutos", "El agujero natural en la roca mide 18 metros de diámetro", "Ideal para snorkel en aguas tranquilas"],
    "mirador-ricardo-roca": ["Parada obligatoria en la costa oeste entre Andratx y Banyalbufar", "Los nidos de cigüeñas son visibles desde el mirador", "El Bar Mirador sirve bebidas con vistas espectaculares"],
    "mirador-ses-animes": ["La Torre des Verger fue construida en el siglo XVI como atalaya", "Aparcamiento gratuito en la carretera principal", "Vista directa sobre los acantilados y la isla de Sa Dragonera"],
    "jardins-alfabia": ["Los jardines tienen influencia árabe del siglo XI", "El paseo de palmeras a la entrada es uno de los más fotografiados de Mallorca", "Las fuentes funcionan en días especiales — consulta el calendario"],
    "can-prunera-soller": ["El museo tiene la mayor colección de Arte Nouveau de Baleares", "La farmacia original en el sótano está perfectamente conservada", "Visita guiada incluida en el precio de la entrada"],
    "casal-solleric-palma": ["El palacio está en el Paseo del Borne, en el corazón de Palma", "Las exposiciones temporales son gratuitas", "El patio interior es un ejemplo perfecto de arquitectura mallorquina"],
    "fundacio-juan-march-palma": ["La colección incluye obras de Picasso, Miró y Dalí", "Entrada gratuita todos los días", "El edificio es del siglo XVIII y fue restaurado magnificamente"],
    "museu-de-mallorca": ["El museo está en el Palau de la Almudaina del siglo XVI", "La sección de arqueología prehistórica es imprescindible", "La colección de pinturas mallorquinas del siglo XIX es sorprendente"],
    "centro-cultural-misericordia": ["Las exposiciones cambian regularmente — consulta la web", "El claustro es un espacio tranquilo en el corazón de Palma", "Entrada gratuita a las exposiciones permanentes"],
    "teatre-principal-palma": ["Compra las entradas con antelación para ópera y ballet", "Las visitas guiadas al edificio son muy interesantes", "La acústica del teatro es considerada excepcional"],
    "museu-art-sacre-palma": ["El museo está junto a la Catedral de Palma", "La colección de orfebrería medieval es única en España", "Entrada combinada disponible con la Catedral"],
    "palma-city": ["El casco histórico es mejor a pie — deja el coche en el parking del Parc de la Mar", "El Passeig del Born es el corazón social de la ciudad", "El mercado de l'Olivar es perfecto para probar productos locales"],
    "fornalutx": ["Considerado uno de los pueblos más bonitos de España", "La plaza central tiene varias terrazas con vistas a la montaña", "El paseo hasta Sóller por el camino histórico tarda 45 minutos"],
    "alcudia": ["Las murallas medievales están perfectamente conservadas", "La zona arqueológica de Pol·lèntia está junto al pueblo", "El mercado del martes y domingo es uno de los más auténticos de Mallorca"],
    "sineu": ["El mercado del miércoles es el más antiguo e importante de Mallorca", "La iglesia de Santa María tiene una de las torres más altas de la isla", "El matadero reconvertido en espacio cultural merece la visita"],
    "banyalbufar": ["Las terrazas de cultivo de la malvasia son las más antiguas de Mallorca", "El mirador de Ses Ànimes está a pocos kilómetros", "Los apartamentos rurales en las antiguas casas de piedra son encantadores"],
    "estellencs": ["El pueblo tiene la plaza de toros más pequeña del mundo", "La playa de guijarros es tranquila y poco masificada", "El camino de la fuente tiene cascadas en primavera"],
    "binissalem": ["La Feria del Vino en octubre es la más importante de Mallorca", "Las bodegas ofrecen visitas y catas gratuitas o a bajo coste", "El pueblo tiene una arquitectura señorial muy bien conservada"],
    "capdepera": ["El castillo medieval está abierto al público con vistas espectaculares", "El mercado de los miércoles es popular entre locales", "El faro próximo tiene vistas hacia Menorca en días claros"],
    "santanyi": ["El mercado del sábado alrededor de la iglesia es imprescindible", "La piedra de marès de color miel da un color único al pueblo", "Muchas galerías de arte locales con obras de artistas residentes"],
    "petra": ["El Museu Fra Junípero Serra narra la vida del misionero fundador de California", "El pueblo tiene una tranquilidad auténtica poco turística", "La bodega familiar Miquel Oliver produce vinos premiados"],
    "puerto-valldemossa": ["El acceso es por una carretera muy estrecha y empinada — cuidado", "El restaurante Bens d'Avall tiene una de las mejores vistas de Mallorca", "La cala es pequeña pero muy pintoresca"],
    "calo-estaca": ["Solo accesible a pie desde la carretera — unos 15 minutos", "Las barquitas de pesca amarradas le dan un ambiente mágico", "El agua es excepcionalmente clara para snorkel"],
    "mirador-estaca": ["Parada perfecta en el recorrido por la costa entre Deià y Valldemossa", "La luz al atardecer es especialmente fotogénica", "Aparcamiento en el arcén de la carretera"],
    "sup-sant-vicenc": ["Alquiler de tablas disponible en la misma playa", "Las aguas de Cala Sant Vicenç son ideales para principiantes", "El kayak también es una opción popular en la zona"],
    "sup-port-pollenca": ["La bahía es perfecta para largas travesías de SUP sin oleaje", "Varios clubs ofrecen clases para todos los niveles", "Los atardeceres sobre la Bahía de Pollença son espectaculares desde la tabla"],
    "sup-portocolom": ["El puerto natural protege de los vientos del norte", "La ruta hasta la faralló exterior dura unas 2 horas", "El agua es increíblemente transparente para ver el fondo"],
    "sup-cala-ratjada": ["Comprueba el parte meteorológico — el cabo puede ser ventoso", "Los acantilados del norte ofrecen una ruta espectacular", "El Faro de Capdepera es el punto de referencia de la ruta"],
    "sup-portals-vells": ["Cuevas prehistóricas accesibles desde el mar en SUP", "El agua turquesa es de las más bonitas del sur", "Evita los días con levante — puede haber oleaje inesperado"],
    "sup-santa-ponsa": ["Bahía grande y protegida, ideal para familias y principiantes", "Los kioscos de alquiler están abiertos de mayo a octubre", "La ruta alrededor del islote de Sa Porrassa es muy recomendable"],
    "sup-camp-de-mar": ["Aguas tranquilas protegidas por el islote de Es Malgrat", "Club náutico con servicio de alquiler y clases", "La distancia corta al islote es perfecta para rutas de media hora"],
    "sup-port-adriano": ["La marina de lujo tiene una escuela de SUP", "El diseño de Philippe Starck crea un ambiente muy especial", "Ruta interesante hacia las calas cercanas del sur"],
    "sup-soller": ["La bahía circular es perfecta para principiantes absolutos", "El Club de Vela ofrece clases y alquiler de equipos", "Los trenes históricos que llegan al puerto son un espectáculo desde el agua"],
    "sup-cala-major": ["Ruta urbana por la costa de Palma con vistas al Castillo de Bellver", "Club de Mar tiene la mejor base para el alquiler", "Combina bien con una visita al castillo tras el SUP"],
    "gtrentals-motorworld": ["Reserva con antelación especialmente en verano", "El circuito de Motorworld es espectacular para pruebas de coches", "El seguro a todo riesgo está incluido en el precio"],
    "rest-can-torrat": ["Prueba el cochinillo asado, la especialidad de la casa", "Lleva efectivo por si acaso, aunque aceptan tarjeta", "El jardín trasero es perfecto para noches de verano"],
    "rest-can-pedro-genova": ["El lechón al horno y el pan con aceite son imprescindibles", "El local es pequeño — reserva con antelación en temporada", "Precio muy razonable para la calidad ofrecida"],
    "rest-illeta-camp-de-mar": ["El restaurante está sobre el agua — acceso por pasarela de madera", "Los arroces y mariscos son la especialidad", "Reserva la mesa en la terraza exterior con antelación"],
    "rest-sa-curva-hipodromo": ["Los domingos hay carreras de caballos — una experiencia única", "El menú del día es uno de los mejores relación calidad-precio de Palma", "Abierto principalmente a mediodía — consulta horarios"],
    "rest-matias-son-ferriol": ["Típico bufé mallorquín con productos de temporada", "Muy popular entre residentes locales — reserva los fines de semana", "Los postres caseros son un punto fuerte"],
    "rest-sa-ximbomba-genova": ["Institución centenaria famosa por sus croquetas y tapas", "El vino de la casa es sorprendentemente bueno", "La terraza en verano es muy animada"],
    "hike-port-des-canonge": ["El acceso en coche por la carretera es de los más escénicos de la isla", "El pequeño bar local sirve tapas sencillas y bebidas", "Pocos turistas llegan hasta aquí — disfruta de la tranquilidad"],
    "faro-ses-salines": ["El acceso es por un camino de tierra desde Colònia de Sant Jordi", "Las salinas cercanas son un paraíso ornitológico", "El atardecer desde el faro es de los más bonitos de la isla"],
    "salt-des-freu": ["Ruta técnica que requiere algo de experiencia en montaña", "Lleva agua suficiente — no hay fuentes en el recorrido", "El salto de agua es especialmente espectacular tras las lluvias de otoño"],
    "sa-foradada": ["El camino desde Son Marroig tarda unos 30 minutos en bajada", "Pide permiso en Son Marroig para acceder al camino privado", "El embarcadero de piedra es ideal para tirarse al mar"],
    "mhares-sea-club-sunset": ["Las sesiones de atardecer comienzan sobre las 18h en verano", "Reserva con días de antelación — las mesas tienen vistas limitadas", "El cóctel de bienvenida está incluido en muchos paquetes"],
    "calas-sur-llucmajor": ["Zona poco conocida con calas vírgenes de difícil acceso", "Un todoterreno facilita el acceso pero no es imprescindible", "El camino de ronda costero une varias calas en una ruta de día"],
    "calo-des-moro": ["Una de las fotos más icónicas de Mallorca — espera cola para la foto perfecta", "Llega antes de las 8h en verano para disfrutarla tranquilo", "El aparcamiento está a 15 minutos a pie — no hay más cerca"],
    "cala-agulla": ["La zona de aparcamiento gratuito está a 1 km de la playa", "El pinar que rodea la playa es ideal para el picnic", "Las olas pueden ser algo fuertes con viento de levante"],
    "cala-mesquida": ["Playa grande con espacio incluso en temporada alta", "El sistema de dunas detrás de la playa está protegido", "Los chiringuitos abren de junio a septiembre"],
    "cala-llombards": ["Una de las calas más elegantes del sur de Mallorca", "El chiringuito en el acantilado es un lugar perfecto para el aperitivo", "El agua verde esmeralda es ideal para fotografías"],
    "playa-de-muro": ["Parte del Parque Natural de s'Albufera — observa aves en el camino", "La playa de bandera azul tiene todos los servicios", "Aparcamiento gratuito disponible fuera de temporada"],
    "cala-salmunia": ["Acceso por un camino privado — respeta las propiedades", "El agua es especialmente tranquila, ideal para kayak", "Una de las calas más tranquilas del sureste"],
    "portals-vells-beach": ["Las cuevas prehistóricas talladas en la roca son fascinantes", "La playa nudista Es Bellu está a pocos minutos a pie", "El chiringuito sirve paella fresca todos los días"],
    "cala-magraner": ["Solo accesible a pie — 30 minutos desde la carretera", "Lleva snorkel — el fondo marino es muy variado", "Las rocas del entorno crean pozas naturales perfectas para niños"],
    "puig-de-randa": ["Tres santuarios en la misma montaña, cada uno con historia", "Ramon Llull fundó el monasterio superior en el siglo XIII", "Las vistas sobre la llanura central de Mallorca son únicas"],
    "son-marroig": ["La antigua finca del Arxiduc tiene un museo con recuerdos personales", "Desde el jardín se accede al camino hacia Sa Foradada", "El templete de mármol de Carrara junto al mar es muy fotogénico"],
    "mirador-na-burguesa": ["Accesible en bicicleta de montaña desde Palma", "Mejor al amanecer para ver Palma despertarse", "El camino de subida está bien señalizado desde Son Rapinya"],
    "talaia-albercutx": ["Una de las cimas menos visitadas del Cap de Formentor", "El sendero desde la carretera no está señalizado — lleva mapa", "Las vistas sobre el cabo y la bahía de Pollença son únicas"],
    "puig-de-maria": ["El monasterio en la cima ofrece habitaciones muy básicas para peregrinos", "La subida desde Pollença dura unos 45 minutos", "Desde la cima se ven las bahías de Pollença y Alcúdia simultáneamente"],
    "santuari-sant-salvador": ["Abierto todo el año con habitaciones de peregrino disponibles", "La cruz monumental y el obelisco son iconos del interior de Mallorca", "Desde la terraza se ven las costas este y sur de la isla"],
    "mirador-coll-gramola": ["Parada perfecta en la ruta Andratx-Banyalbufar", "El mirador tiene parking propio y bancos para descansar", "Vista directa sobre el pueblo de Banyalbufar y sus terrazas"],
    "mercat-olivar": ["El mayor mercado cubierto de Palma, abierto de lunes a sábado", "La planta de arriba tiene bares con desayunos mallorquines", "Los puestos de pescado local son imprescindibles para los amantes del mar"],
    "mercat-san-juan": ["Mercado en el antiguo convento de Sant Felip Neri", "Los sábados hay mercado de productores artesanos", "Restaurantes de alta calidad rodean el mercado"],
    "mercat-pere-garau": ["El mercado más auténtico y popular entre los residentes de Palma", "Los miércoles y sábados tienen la mayor variedad", "Los precios son más bajos que en los mercados turísticos"],
    "mercat-artesanal-palma": ["Solo abierto en temporada turística, de primavera a otoño", "Artesanía mallorquina auténtica — no souvenirs de importación", "Los talleres de demostración en vivo son muy interesantes"],
    "mercat-gastronomic-sineu": ["El mercado del miércoles es el más importante de la Part Forana", "Los animales de granja se subastan por la mañana temprano", "Los quesos y embutidos mallorquines son imprescindibles"],
    "ruta-cala-boquer": ["La ruta empieza en Port de Pollença, fácil acceso en bus", "La cala no tiene arena — es de piedras lisas, lleva esterilla", "Los buitres de Rüppell anidan en los acantilados del valle"],
    "ruta-cala-murta": ["Ruta circular desde el Port de Pollença", "El sendero atraviesa una zona forestal con sombra agradable", "La cala es pequeña pero muy recogida — llega temprano"],
    "ruta-cala-tuent": ["La bajada desde el Coll de Tuent es muy empinada — precaución", "La cala es tranquila al ser difícil de acceder en coche", "El bar de la cala sirve comida muy sencilla pero refrescante"],
    "ruta-cala-varques": ["Ruta en bicicleta muy popular desde Manacor o Porto Cristo", "El sendero final es de tierra y puede ser irregular", "Hay varias cuevas bajo el agua accesibles con snorkel"],
    "ruta-cala-estreta": ["Una de las calas más secretas de la costa este de Mallorca", "El camino de acceso requiere cierta condición física", "Lleva agua y snorkel — el fondo marino es espectacular"],
    "ruta-coll-baix": ["La playa de Coll Baix solo es accesible a pie o en barco", "La bajada final es por terreno rocoso — lleva calzado adecuado", "El agua de color turquesa es de las más bonitas de Mallorca"],
    "gem-cova-ses-bruixes": ["No está señalizado — descarga el mapa offline antes de ir", "La cueva es pequeña pero las formaciones rocosas son impresionantes", "Respeta el entorno — no dejes rastro"],
    "gem-font-de-la-vila": ["La fuente ha abastecido al pueblo durante siglos", "El paseo desde Alaró dura unos 20 minutos por camino de piedra", "Muy pocas personas la visitan — disfruta de la soledad"],
    "gem-bassa-de-can-coll": ["El lago artificial atrae aves acuáticas en invierno", "La finca es privada — respeta los accesos públicos indicados", "Lleva prismáticos si eres aficionado a la ornitología"],
    "gem-mirador-sa-trapa": ["El monasterio en ruinas de Sa Trapa está en el camino", "La vista sobre la isla de Sa Dragonera es la mejor del suroeste", "El ascenso dura unas 2 horas desde Sant Elm"],
    "cala-figuera-santanyi": ["El puerto pesquero mantiene su actividad tradicional", "Los pescadores venden capturas directas desde sus barcas por la mañana", "El camino de ronda alrededor de la cala tiene vistas preciosas"],
    "cala-santanyi": ["El kiosko de la playa sirve buenos helados artesanales", "Las formaciones rocosas en los extremos de la playa son fotogénicas", "Playa bien organizada con hamacas y sombrillas de alquiler"],
    "cala-millor": ["Playa de arena fina de casi 2 km de largo", "Perfecto para familias con niños por las aguas tranquilas", "El paseo marítimo tiene restaurantes para todos los gustos"],
    "port-de-soller-beach": ["El tranvía histórico llega directamente hasta el Puerto", "Las montañas de la Tramuntana de fondo crean un paisaje único", "El Club de Vela organiza excursiones en barco al atardecer"],
    "cala-romantica": ["Aguas tranquilas y arena fina — muy popular entre familias", "El restaurante sobre los acantilados tiene vistas espectaculares", "Aparcamiento gratuito disponible a poca distancia"],
    "cala-barca-andratx": ["Cala escondida entre acantilados accesible solo a pie o en barco", "Las aguas son cristalinas y poco profundas — ideal para snorkel", "Los pescadores del puerto de Andratx la utilizan como refugio"],
    "playa-de-palma": ["El bus C1 desde el centro de Palma llega directamente a la playa", "El paseo marítimo tiene 8 km — ideal para running", "El Balneario 6 es el punto más animado con bares y música"],
    "illetes": ["Una de las playas más elegantes de Mallorca — reserva hamacas online", "El Restaurante Flanigan tiene fama desde los años 70", "El catamaran ferry desde Palma es la forma más cómoda de llegar"],
    "cala-dor": ["Puerto deportivo con ambiente cosmopolita y animado", "Las calitas del entorno son accesibles en kayak de alquiler", "El mercado artesanal de los martes y jueves es muy popular"],
    "peguera": ["Playa de arena fina con todos los servicios", "El paseo central tiene buena oferta gastronómica", "La zona comercial tiene tiendas de buceo y alquiler de motos de agua"],
    "playa-sant-elm": ["Vista directa a la isla de Sa Dragonera — muy fotogénico", "Ferry regular a Sa Dragonera desde el puerto de Sant Elm", "El pueblo mantiene un ambiente tranquilo y auténtico"],
    "cala-llucalcari": ["Solo accesible a pie desde el camino de Deià a Llucalcari", "Una de las calas más íntimas y menos visitadas del noroeste", "El agua es muy profunda junto a las rocas — cuidado con los niños"],
    "avenc-de-son-pou": ["El acceso es gratuito pero requiere linterna y calzado cerrado", "La chimenea calcárea es espectacular desde abajo", "Combina bien con una visita al bosque circundante"],
    "la-comuna-bunyola": ["La red de senderos es extensa — descarga el mapa del Consell de Mallorca", "Ideal para bicicleta de montaña — varios niveles de dificultad", "Los miradores sobre el Pla de Mallorca son magníficos"],
    "punta-negra-sant-vicenc": ["Las rocas volcánicas oscuras contrastan con el agua turquesa", "Snorkel excepcional en las grietas y cuevas submarinas", "Llega en kayak desde Cala Sant Vicenç para la mejor experiencia"],
    "cavall-bernat-coves-blanques": ["Las cuevas son accesibles nadando o en kayak", "El agua dentro de las cuevas tiene un color azul intenso", "El recorrido en kayak desde Cala Sant Vicenç dura unos 30 minutos"],
    "cueva-larga-azul-sant-vicenc": ["La cueva solo es accesible a nado — buena condición física recomendada", "La luz azul dentro de la cueva es más intensa a media mañana", "Lleva gafas de snorkel y aletas para mayor comodidad"],
    "cala-en-basset": ["La torre defensiva del siglo XVI domina la entrada de la cala", "Acceso a pie desde Sant Elm — unos 30 minutos de caminata", "El agua verde esmeralda es perfecta para el baño"],
    "cala-antena": ["Una de las calas más tranquilas del este de Mallorca", "El chiringuito abre solo en temporada alta", "El fondo marino tiene posidonia — snorkel muy recomendable"],
    "cala-virgili": ["Accesible a pie desde Cala d'Or en unos 20 minutos", "La cala tiene solo unos metros de ancho — muy íntima", "El agua verde claro es especialmente bonita al mediodía"],
    "cala-marcal": ["Playa familiar con servicio de socorristas en temporada", "El camping cercano hace que tenga buenos servicios", "Los pedales de alquiler son populares entre familias"],
    "ses-covetes": ["La playa naturista de Es Trenc empieza a pocos minutos a pie", "El kiosko de Es Trenc está a un corto paseo", "El paisaje de dunas detrás de la playa es muy fotogénico"],
    "es-carbo": ["Una de las playas más vírgenes y solitarias del sur", "No hay servicios — lleva todo lo necesario", "El acceso es por una pista de tierra de unos 3 km"],
    "arenal-sa-rapita": ["Puerto deportivo tranquilo con ambiente familiar", "El restaurante del club náutico sirve buen marisco fresco", "La playa tiene aguas muy tranquilas, ideal para niños"],
    "cala-vinyes": ["Las aguas tranquilas son perfectas para familias con niños pequeños", "El restaurante en el acantilado tiene vistas al islote Es Malgrat", "El paseo desde Santa Ponça solo lleva unos 20 minutos"],
    "cap-falco": ["Cala rocosa accesible por un camino forestal desde Portals Vells", "El snorkel es excelente en los fondos rocosos", "El faro del Cap Falcó es el punto de referencia"],
    "gorg-blau": ["El embalse está rodeado de montañas de la Tramuntana", "La carretera de acceso desde Lluc es espectacular", "La ruta del GR221 pasa junto al embalse"],
    "mhares-sea-club": ["Reserva mesa en la terraza con anticipación para el almuerzo", "El acceso desde Cala Figuera es por un camino empinado", "Los días entre semana tienen ambiente más tranquilo que los fines de semana"],
    "mirador-des-colomer": ["Las vistas sobre el Peñón des Colomer y la bahía son impresionantes", "El aparcamiento puede llenarse rápido en verano — llega temprano", "Con buenos prismáticos puedes ver aves rapaces nidificando"],
}

# ── German name overrides (only where significantly different from Spanish/Catalan) ──
NAME_DE = {
    "es-trenc": "Es Trenc", "cala-mondrag": "Cala Mondragó", "formentor-beach": "Strand von Formentor",
    "cala-deia": "Cala Deià", "cala-pi": "Cala Pi", "cala-varques": "Cala Varques",
    "tramuntana-range": "Tramuntana-Gebirge", "barranc-biniaraix": "Schlucht von Biniaraix",
    "puig-major": "Puig Major", "sa-calobra": "Sa Calobra", "seu-cathedral": "Kathedrale La Seu",
    "bellver-castle": "Burg Bellver", "fundacio-miro": "Miró-Stiftung",
    "es-baluard": "Museum Es Baluard", "valldemossa": "Valldemossa",
    "deia": "Deià", "soller": "Sóller", "pollenca": "Pollença",
    "cap-formentor": "Kap Formentor", "mirador-ses-barques": "Aussichtspunkt Ses Barques",
    "restaurant-mola": "Restaurant Es Moli d'en Bou", "restaurant-juanito": "Bar-Restaurant Juanito",
    "mercat-santa-catalina": "Markt Santa Catalina", "bodega-trevin": "Weingut Trevin",
    "coves-drach": "Drachenhöhlen", "kayak-soller": "Kajak Port de Sóller",
    "cami-des-correu": "Postweg Camí des Correu", "castell-alaro": "Burg Alaró",
    "puig-ofre": "Puig de l'Ofre", "puig-tomir": "Puig Tomir",
    "cami-arxiduc": "Erzherzogsweg", "cala-tuent": "Cala Tuent",
    "torrent-pareis": "Torrent de Pareis", "cala-marmols": "Cala Màrmols",
    "monestir-lluc": "Kloster Lluc", "faro-formentor": "Leuchtturm Formentor",
    "sa-foradada": "Sa Foradada", "mirador-ricardo-roca": "Aussichtspunkt Ricardo Roca",
    "mirador-ses-animes": "Aussichtspunkt Ses Ànimes", "jardins-alfabia": "Gärten von Alfàbia",
    "can-prunera-soller": "Can Prunera Museum", "casal-solleric-palma": "Palast Solleric",
    "fundacio-juan-march-palma": "Museum Fundació Juan March", "museu-de-mallorca": "Museum von Mallorca",
    "centro-cultural-misericordia": "Kulturzentrum La Misericòrdia",
    "teatre-principal-palma": "Haupttheater Palma", "museu-art-sacre-palma": "Diözesanmuseum Mallorca",
    "palma-city": "Palma de Mallorca", "fornalutx": "Fornalutx", "alcudia": "Alcúdia",
    "sineu": "Sineu", "banyalbufar": "Banyalbufar", "estellencs": "Estellencs",
    "binissalem": "Binissalem", "capdepera": "Capdepera", "santanyi": "Santanyí",
    "petra": "Petra", "puerto-valldemossa": "Hafen Valldemossa",
    "calo-estaca": "Caló de S'Estaca", "mirador-estaca": "Aussichtspunkt S'Estaca",
    "sup-sant-vicenc": "SUP Cala Sant Vicenç", "sup-port-pollenca": "SUP Port de Pollença",
    "sup-portocolom": "SUP Portocolom", "sup-cala-ratjada": "SUP Cala Ratjada",
    "sup-portals-vells": "SUP Portals Vells", "sup-santa-ponsa": "SUP Santa Ponsa",
    "sup-camp-de-mar": "SUP Camp de Mar", "sup-port-adriano": "SUP Port Adriano",
    "sup-soller": "SUP Port de Sóller", "sup-cala-major": "SUP Cala Major",
    "gtrentals-motorworld": "GTRentals – Motorworld Mallorca",
    "rest-can-torrat": "Ca'n Torrat", "rest-can-pedro-genova": "Mesón Ca'n Pedro",
    "rest-illeta-camp-de-mar": "Restaurant Illeta", "rest-sa-curva-hipodromo": "Bar Sa Curva",
    "rest-matias-son-ferriol": "Ca'n Matias i Miquel", "rest-sa-ximbomba-genova": "Sa Ximbomba",
    "hike-port-des-canonge": "Port des Canonge", "faro-ses-salines": "Leuchtturm Ses Salines",
    "salt-des-freu": "Wasserfall Salt des Freu", "sa-foradada": "Sa Foradada",
    "mhares-sea-club-sunset": "Mhares Sea Club – Sonnenuntergang",
    "calas-sur-llucmajor": "Buchten Süd Llucmajor", "calo-des-moro": "Caló des Moro",
    "cala-agulla": "Cala Agulla", "cala-mesquida": "Cala Mesquida",
    "cala-llombards": "Cala Llombards", "playa-de-muro": "Strand von Muro",
    "cala-salmunia": "Cala s'Almunia", "portals-vells-beach": "Portals Vells Strand",
    "cala-magraner": "Cala Magraner", "puig-de-randa": "Puig de Randa",
    "son-marroig": "Son Marroig", "mirador-na-burguesa": "Aussichtspunkt Na Burguesa",
    "talaia-albercutx": "Talaia d'Albercutx", "puig-de-maria": "Puig de Maria",
    "santuari-sant-salvador": "Heiligtum Sant Salvador",
    "mirador-coll-gramola": "Aussichtspunkt Coll de Sa Gramola",
    "mercat-olivar": "Markt L'Olivar", "mercat-san-juan": "Markt Sant Joan",
    "mercat-pere-garau": "Markt Pere Garau", "mercat-artesanal-palma": "Kunsthandwerksmarkt Palma",
    "mercat-gastronomic-sineu": "Wochenmarkt Sineu",
    "ruta-cala-boquer": "Wanderung Cala Bóquer", "ruta-cala-murta": "Wanderung Cala Murta",
    "ruta-cala-tuent": "Wanderung Cala Tuent", "ruta-cala-varques": "Wanderung Cala Varques",
    "ruta-cala-estreta": "Wanderung Cala Estreta", "ruta-coll-baix": "Wanderung Platja des Coll Baix",
    "gem-cova-ses-bruixes": "Geheimtipp: Cova de Ses Bruixes",
    "gem-font-de-la-vila": "Geheimtipp: Font de la Vila",
    "gem-bassa-de-can-coll": "Geheimtipp: Bassa de Can Coll",
    "gem-mirador-sa-trapa": "Geheimtipp: Aussichtspunkt Sa Trapa",
    "cala-figuera-santanyi": "Cala Figuera", "cala-santanyi": "Cala Santanyí",
    "cala-millor": "Cala Millor", "port-de-soller-beach": "Strand Port de Sóller",
    "cala-romantica": "Cala Romántica", "cala-barca-andratx": "Cala Barca",
    "playa-de-palma": "Strand von Palma", "illetes": "Strand Illetes",
    "cala-dor": "Cala d'Or", "peguera": "Strand Peguera",
    "playa-sant-elm": "Strand Sant Elm", "cala-llucalcari": "Cala Llucalcari",
    "avenc-de-son-pou": "Höhle Avenc de Son Pou", "la-comuna-bunyola": "La Comuna de Bunyola",
    "punta-negra-sant-vicenc": "Punta Negra",
    "cavall-bernat-coves-blanques": "Cavall Bernat & Coves Blanques",
    "cueva-larga-azul-sant-vicenc": "Blaue Höhle (Cueva Azul)",
    "cala-en-basset": "Cala en Basset", "cala-antena": "Cala Antena",
    "cala-virgili": "Cala Virgili", "cala-marcal": "Cala Marçal",
    "ses-covetes": "Strand Ses Covetes", "es-carbo": "Strand Es Carbó",
    "arenal-sa-rapita": "Arenal de Sa Ràpita", "cala-vinyes": "Cala Vinyes",
    "cap-falco": "Cala Cap Falcó", "gorg-blau": "Stausee Gorg Blau",
    "mhares-sea-club": "Mhares Sea Club", "mirador-des-colomer": "Aussichtspunkt s'Colomer",
}

# ── German descriptions (concise, quality travel content) ────────────────────
DESC_DE = {
    "es-trenc": "Einer der unberührtesten Strände Mallorcas mit feinem weißem Sand und klarem türkisfarbenem Wasser im Naturschutzgebiet. Der Strand erstreckt sich über mehrere Kilometer ohne Bebauung.",
    "cala-mondrag": "Wunderschöne Doppelbucht im Naturpark Mondragó. Das klare Wasser und der weiße Sand machen diese Bucht zu einem der beliebtesten Familienziele im Südosten Mallorcas.",
    "formentor-beach": "Legendärer Strand am Ende der gleichnamigen Halbinsel, umgeben von Pinien und Steilklippen. Die Kulisse ist einzigartig – eine der schönsten Buchten der Balearen.",
    "cala-deia": "Kleine Felsenbucht am Fuße des Künstlerdorfes Deià mit kristallklarem Wasser. Das Restaurant Ca's Patro March ist eine der begehrtesten Adressen der ganzen Insel.",
    "cala-pi": "Fjordartige Bucht mit smaragdgrünem Wasser und einem Wachturm auf der Klippe. Besonders bei Familien und Schnorchlern beliebt.",
    "cala-varques": "Wilder und einsamer Strand nur zu Fuß erreichbar. Außergewöhnlich klares Wasser und eine unberührte Naturkulisse machen ihn zu einem Geheimtipp.",
    "tramuntana-range": "UNESCO-Weltnaturerbe seit 2011 – das Tramuntana-Gebirge zieht sich über 90 km entlang der Nordwestküste und beherbergt die höchsten Gipfel und schönsten Wanderwege Mallorcas.",
    "barranc-biniaraix": "Einer der schönsten Wanderwege Mallorcas führt durch diese historische Schlucht. Gepflasterte Wege und Trockensteinmauern zeugen von der jahrhundertealten Kulturlandschaft.",
    "puig-major": "Mit 1.445 m der höchste Gipfel Mallorcas. Militärische Einschränkungen machen den Gipfel selbst unzugänglich, doch die Straße vorbei am Stausee Cúber bietet atemberaubende Ausblicke.",
    "sa-calobra": "Spektakuläre Bucht am Ende der legendären Serpentinenstraße mit 270°-Kurve. Die Zufahrt selbst gilt als einer der schönsten Fahrwege Europas.",
    "seu-cathedral": "Die gotische Kathedrale La Seu thront majestätisch über dem Hafen von Palma. Gaudi-Restaurierungen im Inneren und atemberaubende Fenster machen sie zu einem Meisterwerk.",
    "bellver-castle": "Einzigartiges kreisrundes gotisches Schloss aus dem 14. Jahrhundert auf einer Anhöhe mit Panoramablick über die Bucht von Palma. Im Sommer finden hier Open-Air-Konzerte statt.",
    "fundacio-miro": "Das Atelier und die Stiftung des Malers Joan Miró – original erhalten wie zum Zeitpunkt seines Todes. Ein einzigartiges Zeugnis des kreativen Prozesses eines Weltklassekünstlers.",
    "es-baluard": "Museum für moderne und zeitgenössische Kunst, eingebettet in die historischen Stadtmauern von Palma. Die Dachterrasse bietet spektakuläre Ausblicke über die Stadt.",
    "valldemossa": "Eines der schönsten Dörfer Mallorcas mit gepflasterten Gassen und blumengeschmückten Häusern. Die Kartause, wo Chopin und George Sand den Winter verbrachten, ist das kulturelle Herzstück.",
    "deia": "Malerisches Bergdorf, seit Jahrzehnten Treffpunkt von Künstlern und Intellektuellen. Robert Graves lebte hier – sein Haus ist heute ein Museum.",
    "soller": "Charmantes Orangenstädtchen in einem idyllischen Tal, verbunden mit Palma durch einen historischen Holzzug. Die Jugendstilarchitektur und der Wochenmarkt machen es zu einem Muss.",
    "pollenca": "Wunderschöne Stadt mit römischen Wurzeln, berühmt für die 365 Stufen zur Calvari-Kirche. Der Sonntags-Wochenmarkt um das Kreuzgang ist unverzichtbar.",
    "cap-formentor": "Das dramatische Nordkap Mallorcas mit schwindelerregenden Klippen und dem ikonischen Leuchtturm. Die Fahrt durch die Halbinsel gehört zu den beeindruckendsten Europas.",
    "mirador-ses-barques": "Spektakulärer Aussichtspunkt auf der Straße nach Sóller mit Blick auf den Hafen und die Tramuntana. Das Café serviert die besten Ensaimadas der Region.",
    "restaurant-mola": "Mit einem Michelin-Stern ausgezeichnetes Restaurant inmitten der Tramuntana. Küchenchef Joan Mora verbindet mallorquinische Traditionen mit zeitgenössischer Haute Cuisine.",
    "restaurant-juanito": "Kultige lokale Institution in Manacor, bekannt für authentische mallorquinische Hausmannskost zu fairen Preisen. Seit Jahrzehnten Liebling der Einheimischen.",
    "mercat-santa-catalina": "Das lebhafteste Marktviertel Palmas mit dem historischen Marktgebäude als Herzstück. Tapas-Bars, internationale Restaurants und lokale Händler schaffen ein einzigartiges Ambiente.",
    "bodega-trevin": "Traditionsweingut mit eigenen Rebflächen, das die autochthonen Sorten Mallorcas wie Manto Negro und Prensal Blanc produziert. Führungen und Weinproben auf Anfrage.",
    "coves-drach": "Spektakuläre Tropfsteinhöhlen mit einem der größten unterirdischen Seen der Welt. Das klassische Konzert auf dem See gehört zu den unvergesslichsten Erlebnissen Mallorcas.",
    "kayak-soller": "Seekajaktouren ab dem Hafen von Sóller entlang der Tramuntana-Küste. Höhlenbesichtigungen, Schnorcheln und atemberaubende Klippen inklusive.",
    "cami-des-correu": "Historischer Postweg entlang der Nordwestküste der Tramuntana. Der Pfad verbindet mehrere Dörfer und bietet spektakuläre Meerausblicke.",
    "castell-alaro": "Dramatische mittelalterliche Ruine auf einem Felsen mit 360°-Panorama über Mallorca. Der Aufstieg dauert etwa 2 Stunden – belohnt wird man mit einem unvergesslichen Ausblick.",
    "puig-ofre": "Lohnender Gipfel der Tramuntana auf der Rundwanderung durch die Schlucht von Biniaraix. Der GR221-Fernwanderweg führt über den Gipfel.",
    "puig-tomir": "Abgelegener und lohnender Gipfel im Norden der Tramuntana. Von der Spitze sieht man sowohl die Bucht von Pollença als auch die Bucht von Alcúdia.",
    "cami-arxiduc": "Einer der berühmtesten Kammwege Mallorcas, angelegt vom Erzherzog Ludwig Salvator. Die Route bietet spektakuläre Ausblicke über die Westküste.",
    "cala-tuent": "Abgeschiedene Kieselbucht unter den Steilhängen der Tramuntana. Ruhiger als Sa Calobra nebenan, mit Pinien direkt bis zum Ufer.",
    "torrent-pareis": "Eine der spektakulärsten Naturschluchten Europas mündet hier ins Meer. Der Abstieg erfordert Canyoning-Erfahrung, die Ankunft am Meer ist überwältigend.",
    "cala-marmols": "Einer der abgelegensten und unberührtesten Strände im Süden. Nur zu Fuß oder per Boot erreichbar – kristallklares Wasser belohnt den Aufwand.",
    "monestir-lluc": "Das wichtigste Pilgerziel Mallorcas mit der Schwarzen Madonna. Die Chorknaben (Blauets) singen täglich – ein einzigartiges spirituelles Erlebnis.",
    "faro-formentor": "Der ikonische Leuchtturm am äußersten Ende der Formentor-Halbinsel mit Blick auf offenes Meer. Delfine sind häufig zu sehen.",
    "sa-foradada": "Dramatische Felsenhalbinsel nahe Deià mit einem 18 Meter großen natürlichen Loch im Stein. Der Abstieg von Son Marroig dauert 30 Minuten.",
    "mirador-ricardo-roca": "Beeindruckender Aussichtspunkt an der Westküste zwischen Andratx und Banyalbufar mit Blick auf die Klippen und das offene Meer.",
    "mirador-ses-animes": "Wachturm aus dem 16. Jahrhundert (Torre des Verger) mit direktem Blick auf die Klippen und die Insel Sa Dragonera. Einer der schönsten Aussichtspunkte der Insel.",
    "jardins-alfabia": "Historische Gärten mit maurischen Einflüssen aus dem 11. Jahrhundert. Die Palmpallee am Eingang ist eine der meistfotografierten Attraktionen Mallorcas.",
    "can-prunera-soller": "Perfekt erhaltenes Jugendstilpalais mit der größten Art-Nouveau-Sammlung der Balearen. Das Original-Apothekenlabor im Keller ist ein Highlight.",
    "casal-solleric-palma": "Prachtvolles barockes Stadtpalais am Passeig del Born im Herzen Palmas, heute Kulturzentrum mit wechselnden Ausstellungen. Der Innenhof ist ein Juwel.",
    "fundacio-juan-march-palma": "Bedeutende Sammlung spanischer Kunst des 20. Jahrhunderts mit Werken von Picasso, Miró und Dalí. Eintritt frei, in einem restaurierten Palast aus dem 18. Jahrhundert.",
    "museu-de-mallorca": "In einem Renaissance-Palast untergebracht – die umfassendste Sammlung zur Geschichte und Kultur Mallorcas von der Vorgeschichte bis zur Gegenwart.",
    "centro-cultural-misericordia": "Großes zeitgenössisches Kunst- und Kulturzentrum im historischen Kreuzgang. Ein ruhiger Ort inmitten des Altstadtgetümmels.",
    "teatre-principal-palma": "Die Oper Mallorcas – ein prachtvoll restauriertes Theatergebäude aus dem 18. Jahrhundert mit exzellenter Akustik und anspruchsvollem Spielplan.",
    "museu-art-sacre-palma": "Im Bischofspalast neben der Kathedrale untergebracht – herausragende Sammlung mittelalterlicher Sakralkunst und Goldschmiedearbeiten.",
    "palma-city": "Die lebendige Hauptstadt Mallorcas verbindet arabisches Erbe, gotische Kathedrale und modernistische Architektur mit einem pulsierenden Straßen- und Gastronomieangebot.",
    "fornalutx": "Als eines der schönsten Dörfer Spaniens ausgezeichnet – Fornalutx besticht durch sein harmonisches Ensemble aus Natursteingebäuden, Terrassen und Bergpanorama.",
    "alcudia": "Mustergültig erhaltene mittelalterliche Stadtmauern umgeben das historische Altstadtzentrum. Die römische Ausgrabungsstätte Pol·lèntia liegt direkt am Ortsrand.",
    "sineu": "Das geografische Herzzentrum Mallorcas ist bekannt für seinen riesigen Mittwochsmarkt, den ältesten und bedeutendsten der Insel.",
    "banyalbufar": "An die Nordwestküste geklammert mit jahrhundertealten Terrassenfeldern für den Malvasia-Wein. Eines der pittoreskesten Dörfer der Tramuntana.",
    "estellencs": "Die kleinste Gemeinde Mallorcas liegt auf einem Bergsporn mit Blick aufs Meer. Kaum Tourismus, viel Authentizität und eine enge Verbindung zur Landwirtschaft.",
    "binissalem": "Die Weinhauptstadt Mallorcas inmitten der Ebene. Mehrere Weingüter bieten Führungen an, und im Oktober lockt die größte Weinferia der Insel.",
    "capdepera": "Kleinstädtchen auf einem Hügel mit beeindruckender mittelalterlicher Burg. An klaren Tagen ist von der Burgmauer Menorca zu sehen.",
    "santanyi": "Eleganter Marktflecken im Süden mit charakteristischer honigfarbener Marès-Architektur. Zahlreiche Galerien und ein lebhafter Samstagswochenmarkt.",
    "petra": "Stilles Ackerbauernstädtchen, Geburtsort von Fray Junípero Serra, dem Gründer der Franziskanermissionen in Kalifornien. Das Museum zu seinem Leben ist sehenswert.",
    "puerto-valldemossa": "Winziger und idyllischer Fischerhafen, zu Fuß oder per Auto über eine abenteuerliche enge Straße erreichbar. Traumhafter Blick auf die Tramuntana.",
    "calo-estaca": "Magisches kleines Fischereibucht mit charakteristischen Booten und außergewöhnlich klarem Wasser. Der Abstieg von der Hauptstraße dauert etwa 15 Minuten.",
    "mirador-estaca": "Spektakulärer Küstenaussichtspunkt zwischen Deià und Valldemossa. Das Abendlicht taucht die Steilküste in warmes Gold.",
    "sup-sant-vicenc": "Eines der besten SUP-Startpunkte Mallorcas – das klare, ruhige Wasser der Bucht ist ideal für Anfänger und Fortgeschrittene.",
    "sup-port-pollenca": "Die breite, geschützte Bucht von Port de Pollença ist perfekt für lange SUP-Ausfahrten und gilt als ideales Übungsgebiet.",
    "sup-portocolom": "Der natürliche Hafen von Portocolom schützt vor Nordwinden und bietet kristallklares Wasser für unvergessliche SUP-Touren.",
    "sup-cala-ratjada": "Das raue Nordostkap bietet erfahrenen Paddlern spektakuläre Küstentouren entlang wilder Klippen und kleiner Buchten.",
    "sup-portals-vells": "Dramatische SUP-Destination mit Zugang zu prähistorischen Höhlen vom Wasser aus und türkisfarbenem Wasser.",
    "sup-santa-ponsa": "Große und geschützte Bucht – ideal für Familien und Einsteiger. Mehrere Verleihanbieter direkt am Strand.",
    "sup-camp-de-mar": "Ruhiger SUP-Einstieg für Anfänger, geschützt durch die kleine Insel Es Malgrat. Kurze Ausfahrten zum Eiland sind sehr beliebt.",
    "sup-port-adriano": "Ab der ikonischen Luxusmarina von Philippe Starck bieten sich Küstentouren zu den umliegenden Buchten an.",
    "sup-soller": "Die kreisrunde Bucht von Port de Sóller ist einer der sichersten und schönsten SUP-Orte der Insel – mit Tramuntana-Kulisse.",
    "sup-cala-major": "Städtische SUP-Route entlang der Küste von Palma mit Blick auf die Burg Bellver – leicht erreichbar vom Stadtzentrum.",
    "gtrentals-motorworld": "Supersportwagen-Verleih auf dem Motorworld-Gelände Mallorca. Lamborghini, Ferrari und Porsche für unvergessliche Ausfahrten über die Insel.",
    "rest-can-torrat": "Mallorquinische Institution seit 1972 mit dem besten Spanferkel der Insel. Rustikales Ambiente, Holzofen, unvergessliche Hausmannskost.",
    "rest-can-pedro-genova": "Seit 1976 eines der beliebtesten Restaurants des Stadtteils Gènova – berühmt für sein Spanferkel aus dem Holzofen und hausgemachte Desserts.",
    "rest-illeta-camp-de-mar": "Einzigartiges Restaurant auf einem kleinen Eiland – erreichbar über einen Holzsteg. Fisch und Meeresfrüchte direkt vom Meer.",
    "rest-sa-curva-hipodromo": "Beliebte lokale Bar-Restaurant auf der Pferderennbahn Son Pardo. Authentische mallorquinische Küche und sonntags Pferderennen.",
    "rest-matias-son-ferriol": "Typisches mallorquinisches Büfettrestaurant mit saisonalen Produkten, sehr beliebt bei den Einheimischen.",
    "rest-sa-ximbomba-genova": "Jahrhundertealte Institution in Gènova mit hervorragenden Kroketten, Tapas und einem sehr guten Hauswein.",
    "hike-port-des-canonge": "Winziger, perfekt erhaltener Fischereihafen mit einer der malerischsten Anfahrten der Insel. Ruhig, authentisch und wenig besucht.",
    "faro-ses-salines": "Der südlichste Leuchtturm Mallorcas in den Salinen – umgeben von Flamingos und anderen Zugvögeln. Traumhafter Sonnenuntergang.",
    "salt-des-freu": "Dramatische Schluchtenwanderung durch die enge Schlucht von Son Lluís. Der Wasserfall ist nach Herbstregen besonders beeindruckend.",
    "sa-foradada": "Dramatische Felsenhalbinsel mit einem 18 m großen natürlichen Loch – Wahrzeichen der Westküste nahe Deià.",
    "mhares-sea-club-sunset": "Exklusiver Beach Club an der Ostküste mit Sonnenuntergangs-Sessions. Cocktails, Musik und spektakulärer Meerblick.",
    "calas-sur-llucmajor": "Wenig bekannte Zone mit unberührten Buchten – ideal für Abenteurer, die abseits des Tourismus Mallorca entdecken wollen.",
    "calo-des-moro": "Eine der ikonischsten Buchten Mallorcas – smaragdgrünes Wasser zwischen weißen Felsen. Sehr früh kommen, um die Ruhe zu genießen.",
    "cala-agulla": "Großer Strand bei Cala Ratjada mit feinem Sand und Pinienwald im Hintergrund. Sehr beliebt bei Familien.",
    "cala-mesquida": "Breiter natürlicher Strand mit geschütztem Dünensystem. Weniger überfüllt als andere Strände im Nordosten.",
    "cala-llombards": "Elegante smaragdgrüne Bucht im Süden – eine der fotogenischsten der Insel. Das Kliff-Restaurant ist ein besonderer Genuss.",
    "playa-de-muro": "Langer Sandstrand am Rand des Naturparks s'Albufera. Blaue Flagge, alle Einrichtungen, ideal für Familien.",
    "cala-salmunia": "Ruhige Bucht im Südosten mit außergewöhnlich klarem Wasser – ideal für Kajak und Schnorcheln.",
    "portals-vells-beach": "Breiter Strand mit prähistorischen Felsenhöhlen. FKK-Bereich gleich nebenan, Paella frisch täglich.",
    "cala-magraner": "Kleines Felsenparadies nur zu Fuß erreichbar – hervorragendes Schnorcheln in natürlichen Felspools.",
    "puig-de-randa": "Heiliger Berg mit drei Klöstern – Ramon Llull gründete hier im 13. Jahrhundert die erste Missionsschule. Panorama über die gesamte Zentralebene.",
    "son-marroig": "Das Landgut des Erzherzogs Ludwig Salvator mit Museum und dem berühmten Marmortempel am Meer. Startpunkt für den Abstieg nach Sa Foradada.",
    "mirador-na-burguesa": "Aussichtspunkt im Grünen über Palma – ideal bei Sonnenaufgang. Per Mountainbike ab Palma erreichbar.",
    "talaia-albercutx": "Wenig besuchter Gipfel am Cap de Formentor mit einzigartigen Ausblicken auf den Cabo und die Bucht von Pollença.",
    "puig-de-maria": "Kloster auf dem Gipfel mit einfachen Pilgerzimmern und unglaublichem Panorama über beide Buchten – Pollença und Alcúdia.",
    "santuari-sant-salvador": "Heiligtum auf dem höchsten Punkt des Llevant mit riesigem Kreuz und Obelisk. Von der Terrasse sieht man die Ost- und Südküste gleichzeitig.",
    "mirador-coll-gramola": "Perfekter Aussichtspunkt auf der Strecke Andratx–Banyalbufar mit Blick auf die Terrassenfelder und das Dorf.",
    "mercat-olivar": "Der größte überdachte Markt Palmas – frischer Fisch, lokales Gemüse und mallorquinische Delikatessen unter einem Dach.",
    "mercat-san-juan": "Markt in einem historischen Konvent – samstags mit Handwerkermarkt und umgeben von erstklassigen Restaurants.",
    "mercat-pere-garau": "Der authentischste Markt Palmas – Stammplatz der Einheimischen mit den günstigsten Preisen der Stadt.",
    "mercat-artesanal-palma": "Saisonaler Kunsthandwerksmarkt mit echter mallorquinischer Handarbeit – keine importierten Souvenirs.",
    "mercat-gastronomic-sineu": "Der bedeutendste Wochenmarkt des mallorquinischen Hinterlandes – mittwochs mit Viehmarkt und lokalen Spezialitäten.",
    "ruta-cala-boquer": "Einfache Wanderung durch das Tal Vall de Bóquer zu einer steinigen Bucht. Geierkolonien und weite Ausblicke auf die Bucht von Pollença.",
    "ruta-cala-murta": "Rundwanderung ab Port de Pollença durch schattenreichen Kiefernwald zu einer intimen Bucht.",
    "ruta-cala-tuent": "Abstecher von der Tramuntana-Hauptroute zu einer ruhigen Bucht – etwas anspruchsvoll aber lohnenswert.",
    "ruta-cala-varques": "Beliebte Radtour ab Manacor oder Porto Cristo zu einer wilden Naturbucht mit Unterwasserhöhlen.",
    "ruta-cala-estreta": "Geheimtipp an der Ostküste – die Wanderung zur Cala Estreta führt durch unberührte Natur zu einem außergewöhnlich klaren Wasser.",
    "ruta-coll-baix": "Der Strand Coll Baix gilt als einer der schönsten Mallorcas – nur zu Fuß oder per Boot erreichbar, mit türkisblauem Wasser.",
    "gem-cova-ses-bruixes": "Unbekannte Höhle mit beeindruckenden Gesteinsformationen – kein Touristenrummel, nur Stille und Natur.",
    "gem-font-de-la-vila": "Historische Quelle, die Alaró seit Jahrhunderten versorgt – ein ruhiger Spaziergang auf gepflastertem Weg.",
    "gem-bassa-de-can-coll": "Kleiner Stausee mit Zugvögeln im Winter – ein Geheimtipp für Ornithologen.",
    "gem-mirador-sa-trapa": "Geheimaussichtspunkt über dem Kloster Sa Trapa mit dem besten Blick auf die Insel Sa Dragonera.",
    "cala-figuera-santanyi": "Aktiver Fischerhafen mit charakteristischen weißen Häuschen direkt am Wasser. Morgens verkaufen Fischer ihren Fang direkt vom Boot.",
    "cala-santanyi": "Hübsche Bucht mit feinem Sand und smaragdgrünem Wasser. Liegestühle und Sonnenschirme verleihbar, kleines Café.",
    "cala-millor": "Breiter Sandstrand von fast 2 km Länge – einer der längsten Mallorcas und ideal für Familien.",
    "port-de-soller-beach": "Stadtnaher Strand mit historischer Straßenbahnanbindung und Bergkulisse der Tramuntana. Abendliche Bootsausflüge sehr empfehlenswert.",
    "cala-romantica": "Familienfreundliche Bucht mit feinem Sand und ruhigem Wasser. Das Kliff-Restaurant bietet spektakuläre Ausblicke.",
    "cala-barca-andratx": "Versteckte Bucht zwischen Steilklippen – nur zu Fuß oder per Boot erreichbar mit sehr klarem Wasser.",
    "playa-de-palma": "Acht Kilometer Sandstrand vor den Toren der Hauptstadt – lebhafter Strandpromenade, Wasserportangebote und alle Einrichtungen.",
    "illetes": "Einer der elegantesten Strände Mallorcas mit kristallklarem flachem Wasser. Reservierung der Liegestühle empfohlen.",
    "cala-dor": "Mondäner Jachthafen mit Café-Promenade und kleinen umgebenden Buchten – ideal für Wasserradfahrten.",
    "peguera": "Breiter Sandstrand mit vollständigen Einrichtungen. Die zentrale Fußgängerzone hat gastronomische Vielfalt.",
    "playa-sant-elm": "Direkter Blick auf die Insel Sa Dragonera – mit Fähre erreichbar. Das Dorf ist ruhig und authentisch.",
    "cala-llucalcari": "Eine der intimsten und am wenigsten besuchten Buchten der Nordwestküste – nur zu Fuß durch ein malerisches Bergdorf erreichbar.",
    "avenc-de-son-pou": "Faszinierende natürliche Dolomitkammer mit einem Lichtkegel von oben – kostenlos zugänglich, Taschenlampe und festes Schuhwerk mitbringen.",
    "la-comuna-bunyola": "Ausgedehntes Wandergebiet in den Tramuntana-Ausläufern mit Aussichtspunkten über die Zentralebene – ideal auch für Mountainbiker.",
    "punta-negra-sant-vicenc": "Vulkanische schwarze Felsen im Kontrast zum türkisfarbenen Wasser – hervorragendes Schnorcheln in Ritzen und kleinen Höhlen.",
    "cavall-bernat-coves-blanques": "Malerische Küstenformation mit weißen Kalksteinhöhlen – per Kajak ab Cala Sant Vicenç in ca. 30 Minuten erreichbar.",
    "cueva-larga-azul-sant-vicenc": "Atemberaubende Meereshöhle mit intensivem Blaulicht – nur zu Fuß erreichbar und ein unvergessliches Erlebnis für gute Schwimmer.",
    "cala-en-basset": "Smaragdgrüne Bucht mit einem Wachturm aus dem 16. Jahrhundert – fußläufig von Sant Elm, abseits der Massentouristen.",
    "cala-antena": "Ruhige Bucht im Osten mit Posidonia-Seegras auf dem Meeresgrund – ideal für Schnorcheln.",
    "cala-virgili": "Winzige, nur wenige Meter breite Bucht nahe Cala d'Or – außergewöhnlich klares hellgrünes Wasser.",
    "cala-marcal": "Familienfreundlicher Strand mit Rettungsschwimmern in der Saison. Wasserpedale für Kinder sehr beliebt.",
    "ses-covetes": "Strand mit Pinienwald und Dünenlandschaft. FKK-Bereich Es Trenc liegt nur wenige Gehminuten entfernt.",
    "es-carbo": "Einer der wildesten und einsamsten Strände im Süden – kein Service, nur Natur und Stille. Zufahrt auf Sandpiste.",
    "arenal-sa-rapita": "Ruhiger Familienhafen mit kleinem Sportbootclub und frischem Meeresfrüchten im Hafenrestaurant.",
    "cala-vinyes": "Ruhige Bucht mit Blick auf das Eiland Es Malgrat – fußläufig von Santa Ponça, ideal für kleine Kinder.",
    "cap-falco": "Felsige Bucht am Ende eines Waldweges von Portals Vells – ausgezeichnetes Schnorcheln auf steinigem Grund.",
    "gorg-blau": "Stausee inmitten der Tramuntana-Berge – der GR221-Fernwanderweg führt direkt vorbei. Imposante Bergkulisse.",
    "mhares-sea-club": "Exklusiver Strand-Club an der Ostküste mit gehobener Gastronomie – an Wochentagen ruhiger als am Wochenende.",
    "mirador-des-colomer": "Dramatischer Aussichtspunkt über den Felsen des Colomer und die Bucht von Pollença – einer der spektakulärsten der Insel.",
}

# ── German tips translations ──────────────────────────────────────────────────
TIPS_DE = {
    "es-trenc": ["Im Sommer vor 10 Uhr ankommen", "FKK-Zone am westlichen Ende", "Parkplätze füllen sich schnell – Busverbindung ab Campos nutzen"],
    "cala-mondrag": ["Teil eines geschützten Naturparks", "Zwischen den zwei Buchten wandern", "Hervorragendes Schnorcheln zwischen den Felsen"],
    "formentor-beach": ["In der Hauptsaison per Boot ab Port de Pollença anreisen", "Früh ankommen – Parkplatz ist begrenzt", "Die Fahrt durch Cap de Formentor ist spektakulär"],
    "cala-deia": ["10 Minuten Fußweg bergab vom Dorf Deià", "Tisch im Restaurant Ca's Patro March für Meeresfrüchte reservieren", "Felsküste – Wasserschuhe empfohlen"],
    "cala-pi": ["Schmale fjordartige Bucht – ideal für Kinder", "Auf den Wachturm wandern für Panoramablick", "Begrenzter Parkplatz in der Hochsaison"],
    "cala-varques": ["Nur zu Fuß erreichbar – ca. 20 Minuten von der Straße", "Wasser und Proviant mitbringen, keine Einrichtungen vor Ort", "Außergewöhnliches Schnorcheln in klarem Wasser"],
    "tramuntana-range": ["UNESCO-Weltnaturerbe seit 2011", "Aussichtspunkt Ses Barques bietet die besten Ausblicke", "Die beliebteste Route ist der Camí de s'Arxiduc"],
    "barranc-biniaraix": ["Start im Dorf Biniaraix am Rand von Sóller", "Historisches Pflaster kann nass rutschig sein", "Festes Wanderschuhwerk tragen"],
    "puig-major": ["Der Gipfel ist wegen militärischer Anlagen gesperrt", "Bester Aussichtspunkt von der Straße neben dem Gipfel", "Der Stausee Cúber am Fuß ist sehr fotogen"],
    "sa-calobra": ["Die 270°-Spiralstraße ist legendär", "Mit der Fähre ab Sóller anreisen um Staus zu vermeiden", "Der Torrent neben dem Strand führt zu einer versteckten Bucht"],
    "seu-cathedral": ["Bei Sonnenuntergang besuchen wenn Licht durch die Fenster fällt", "Gaudís Gerüst ist fester Teil des Innenraums", "Ansicht vom Parc de la Mar bei Sonnenaufgang ist unvergesslich"],
    "bellver-castle": ["Aussicht über die Bucht von Palma ist atemberaubend", "Sommerkonzerte in der Burg sind sehr beliebt", "Der umliegende Wald eignet sich gut zum Spazierengehen"],
    "fundacio-miro": ["Mirós Atelier wurde genau so erhalten wie er es verließ", "Der Museumsshop hat einzigartige Reproduktionen", "Die Terrasse mit Meerblick ist einen Besuch wert"],
    "es-baluard": ["Museumsdachterrasse bietet spektakuläre Aussicht über Palma", "Freitagnachmittags freier Eintritt", "Integration des Museums in historische Stadtmauern ist einzigartig"],
    "valldemossa": ["Chopins und George Sands Winter 1838-39 in der Kartause besichtigen", "Die Kartause ist das meiste Jahr geöffnet", "Der Sonntagsmarkt ist sehr gemütlich"],
    "deia": ["Die Cala Deià ist ein kleines Felsenparadies – 10 Minuten zu Fuß", "Sommerterrassen im Voraus reservieren", "Der Friedhof mit Meerblick ist einer der schönsten Europas"],
    "soller": ["Historische Straßenbahn verbindet Dorf und Hafen", "Der Holzzug ab Palma dauert 1 Stunde und lohnt sich sehr", "Der Samstagmarkt ist der authentischste des Tals"],
    "pollenca": ["Die 365 Stufen zur Calvari-Kirche führen zu spektakulärer Aussicht", "Sonntagsmarkt um den Kreuzgang ist unverzichtbar", "Font de Sant Jordi ideal für Familien"],
    "cap-formentor": ["Die Straße kann im Sommer gesperrt sein – Beschränkungen prüfen", "Vor 9 Uhr am Leuchtturm ankommen um Menschenmassen zu vermeiden", "Nistende Mauersegler in den Felswänden sind faszinierend"],
    "mirador-ses-barques": ["Pflichthauptstop auf der Straße von Sóller zum Hafen", "Das Café des Aussichtspunktes serviert die besten Ensaimadas der Region", "Besonders schön bei Sonnenuntergang"],
    "restaurant-mola": ["Menü-Degustationen Monate im Voraus buchen", "Küchenchef Joan Mora arbeitet mit lokalen Erzeugern", "Die Weinbegleitung mit mallorquinischen Weinen ist hervorragend"],
    "restaurant-juanito": ["Berühmt für hausgemachte Kroketten und Pan amb sobrassada", "Nur Bargeld – lokale Währung mitbringen", "Früh kommen, da Schlangen sich schnell bilden"],
    "mercat-santa-catalina": ["Markt von Montag bis Samstag morgens geöffnet", "Die Bars ringsum servieren authentische mallorquinische Frühstücke", "Das Viertel hat das beste Gastroangebot Palmas"],
    "bodega-trevin": ["Führungen mit Wein- und Olivenölverkostung inbegriffen", "Manto Negro ist die typische Rotweinsorte Mallorcas", "Im Voraus für geführte Touren anrufen"],
    "coves-drach": ["Besuche mit festen Zeitplänen – Tickets online kaufen", "Klassikkonzert auf dem Untergrundseee ist unvergesslich", "Innentemperatur 21°C – eine Jacke mitnehmen"],
    "kayak-soller": ["Sonnenuntergangstouren am beliebtesten – Tage im Voraus buchen", "Längere Routen erfordern gute Fitness", "Schnorcheln in Höhlen und vor Felswänden inklusive"],
    "cami-des-correu": ["Pfad verbindet mehrere historische Ortschaften der Küste", "Offline-Karte herunterladen da Beschilderung lückenhaft", "Bester Zeitraum Frühling und Herbst wegen der Hitze"],
    "castell-alaro": ["Aufstieg ab Alaró dauert ca. 2 Stunden", "Die Schutzhütte oben serviert einfache Hausmannskost", "360°-Panorama zum Orientieren über ganz Mallorca"],
    "puig-ofre": ["Rundwanderung ab der Schlucht Barranc de Biniaraix", "GR221-Fernwanderweg führt über den Gipfel", "Endemische Tramuntana-Pflanzen im Frühling sichtbar"],
    "puig-tomir": ["Startpunkt am Coll de Sa Bataia", "Echte Bergwanderung – angemessene Ausrüstung mitbringen", "Vom Gipfel sind Bucht von Pollença und Bucht von Alcúdia sichtbar"],
    "cami-arxiduc": ["Route beginnt in Valldemossa oder Son Gual", "Kammabschnitte können schwindelerregend sein – nicht für Ängstliche", "Erzherzog Ludwig Salvator baute diesen Weg zur Erkundung"],
    "cala-tuent": ["Zufahrtsstraße ist eng und kurvenreich", "Familien bevorzugen das nahe Sa Calobra", "Pinien bis ans Ufer schaffen angenehmen Schatten"],
    "torrent-pareis": ["Abstieg durch die Schlucht erfordert Canyoning-Erfahrung", "Bei Regen gefährlich – Wetter vorher prüfen", "Das Einmünden ins Meer zwischen Klippen ist spektakulär"],
    "cala-marmols": ["Nur zu Fuß ab Es Carbó oder per Boot erreichbar", "Einer der wenigen unberührten Strände im Süden Mallorcas", "Außergewöhnlich klares Wasser zum Schnorcheln"],
    "monestir-lluc": ["Das Kloster ist das spirituelle Herz Mallorcas", "Die Chorknaben (Blauets) treten regelmäßig auf – Zeiten erfragen", "Der Rundweg ums Kloster hat wunderschöne Ausblicke"],
    "faro-formentor": ["Die Straße kann in der Hochsaison für Privatfahrzeuge gesperrt sein", "Busverbindung ab Pollença ist die bequemste Option", "Delfine werden häufig vom Leuchtturm aus gesichtet"],
    "sa-foradada": ["Weg ab Son Marroig dauert ca. 30 Minuten", "Das natürliche Loch im Stein hat 18 Meter Durchmesser", "Ideal zum Schnorcheln in ruhigem Wasser"],
    "mirador-ricardo-roca": ["Pflichthaltemacht an der Westküste zwischen Andratx und Banyalbufar", "Storchennester vom Aussichtspunkt sichtbar", "Bar Mirador serviert Getränke mit spektakulärer Aussicht"],
    "mirador-ses-animes": ["Der Wachturm Torre des Verger wurde im 16. Jahrhundert erbaut", "Kostenloser Parkplatz an der Hauptstraße", "Direkter Blick auf Klippen und die Insel Sa Dragonera"],
    "jardins-alfabia": ["Die Gärten stammen aus dem 11. Jahrhundert mit maurischem Einfluss", "Die Palmenallee am Eingang ist das meistfotografierte Motiv", "Brunnen funktionieren an Sondertagen – Kalender prüfen"],
    "can-prunera-soller": ["Das Museum hat die größte Jugendstil-Sammlung der Balearen", "Das ursprüngliche Apothekenlabor im Keller ist ein Highlight", "Geführte Tour im Eintrittspreis inbegriffen"],
    "casal-solleric-palma": ["Der Palast liegt am Passeig del Born im Herzen Palmas", "Wechselausstellungen kostenlos", "Der Innenhof ist ein Juwel mallorquinischer Architektur"],
    "fundacio-juan-march-palma": ["Die Sammlung umfasst Werke von Picasso, Miró und Dalí", "Täglich kostenloser Eintritt", "Das Gebäude aus dem 18. Jahrhundert wurde meisterhaft restauriert"],
    "museu-de-mallorca": ["Das Museum befindet sich in einem Renaissance-Palast aus dem 16. Jahrhundert", "Die Abteilung für vorgeschichtliche Archäologie ist unverzichtbar", "Die Sammlung mallorquinischer Malerei des 19. Jahrhunderts ist überraschend"],
    "centro-cultural-misericordia": ["Ausstellungen wechseln regelmäßig – Website besuchen", "Der Kreuzgang ist ein ruhiger Ort mitten in Palma", "Eintritt zu Dauerausstellungen kostenlos"],
    "teatre-principal-palma": ["Tickets für Oper und Ballett frühzeitig kaufen", "Führungen durch das Gebäude sind sehr interessant", "Die Akustik gilt als außergewöhnlich gut"],
    "museu-art-sacre-palma": ["Das Museum liegt neben der Kathedrale von Palma", "Die mittelalterliche Goldschmiedesammlung ist einzigartig in Spanien", "Kombiticket mit der Kathedrale erhältlich"],
    "palma-city": ["Altstadt am besten zu Fuß erkunden – Parken am Parc de la Mar", "Der Passeig del Born ist das gesellschaftliche Zentrum der Stadt", "Der Mercat de l'Olivar ist ideal zum Probieren lokaler Produkte"],
    "fornalutx": ["Als eines der schönsten Dörfer Spaniens ausgezeichnet", "Der Dorfplatz hat mehrere Terrassen mit Bergblick", "Fußweg nach Sóller dauert ca. 45 Minuten"],
    "alcudia": ["Die mittelalterlichen Stadtmauern sind mustergültig erhalten", "Römische Ausgrabungsstätte Pol·lèntia direkt am Ortsrand", "Markt dienstags und sonntags, einer der authentischsten Mallorcas"],
    "sineu": ["Der Mittwochsmarkt ist der älteste und bedeutendste Mallorcas", "Die Kirche Santa María hat einen der höchsten Türme der Insel", "Das zum Kulturzentrum umgebaute Schlachthaus ist einen Besuch wert"],
    "banyalbufar": ["Die Terrassenfelder für Malvasia-Wein sind die ältesten Mallorcas", "Der Aussichtspunkt Ses Ànimes liegt wenige Kilometer entfernt", "Landhäuser aus altem Stein bieten charmante Unterkunft"],
    "estellencs": ["Das Dorf hat die kleinste Stierkampfarena der Welt", "Der Kieselstrand ist ruhig und wenig besucht", "Der Quellweg hat im Frühling kleine Wasserfälle"],
    "binissalem": ["Die Weinferia im Oktober ist die bedeutendste der Insel", "Weingüter bieten kostenlose oder günstige Führungen an", "Das Dorf hat eine gut erhaltene herrschaftliche Architektur"],
    "capdepera": ["Die mittelalterliche Burg ist öffentlich zugänglich mit spektakulärer Aussicht", "Der Mittwochsmarkt ist bei Einheimischen sehr beliebt", "Der nahegelegene Leuchtturm bietet Ausblicke bis Menorca"],
    "santanyi": ["Der Samstagswochenmarkt rund um die Kirche ist unverzichtbar", "Der honigfarbene Marès-Sandstein gibt dem Ort seinen einzigartigen Charakter", "Viele lokale Kunstgalerien mit Werken ansässiger Künstler"],
    "petra": ["Das Museum Fray Junípero Serra erzählt das Leben des Missionsgründers", "Das Dorf hat eine unverfälschte Authentizität abseits des Tourismus", "Das Familienweingut Miquel Oliver produziert preisgekrönte Weine"],
    "puerto-valldemossa": ["Zufahrt über sehr enge steile Straße – Vorsicht", "Restaurant Bens d'Avall hat eine der schönsten Aussichten Mallorcas", "Die Bucht ist klein aber sehr malerisch"],
    "calo-estaca": ["Nur zu Fuß von der Straße – ca. 15 Minuten", "Die festgemachten Fischerboote verleihen einen magischen Charme", "Außergewöhnlich klares Wasser zum Schnorcheln"],
    "mirador-estaca": ["Idealer Stop auf der Küstenfahrt zwischen Deià und Valldemossa", "Das Abendlicht ist besonders fotogen", "Parken am Straßenrand"],
    "sup-sant-vicenc": ["Verleih direkt am Strand verfügbar", "Die Gewässer von Cala Sant Vicenç sind ideal für Anfänger", "Kajak ist ebenfalls eine beliebte Option in der Gegend"],
    "sup-port-pollenca": ["Die Bucht ist perfekt für lange SUP-Ausfahrten ohne Wellengang", "Mehrere Clubs bieten Kurse für alle Niveaus an", "Sonnenuntergänge über der Bucht von Pollença vom Brett aus sind spektakulär"],
    "sup-portocolom": ["Der natürliche Hafen schützt vor Nordwinden", "Die Route zum äußeren Felsvorsprung dauert ca. 2 Stunden", "Das Wasser ist außergewöhnlich klar um den Grund zu sehen"],
    "sup-cala-ratjada": ["Wettervorhersage prüfen – das Kap kann windig sein", "Die Klippen im Norden bieten eine spektakuläre Route", "Der Leuchtturm Capdepera ist der Orientierungspunkt"],
    "sup-portals-vells": ["Prähistorische Höhlen vom Meer aus per SUP erreichbar", "Das türkisfarbene Wasser ist das schönste im Süden", "Levante-Wind meiden – kann unerwarteten Wellengang verursachen"],
    "sup-santa-ponsa": ["Große und geschützte Bucht, ideal für Familien und Anfänger", "Verleihkioske von Mai bis Oktober geöffnet", "Route um das Eiland Sa Porrassa sehr empfehlenswert"],
    "sup-camp-de-mar": ["Ruhiges Wasser geschützt durch das Eiland Es Malgrat", "Nautikclub mit Verleih und Kursen", "Kurze Distanz zum Eiland ideal für halbstündige Touren"],
    "sup-port-adriano": ["Die Luxusmarina hat eine SUP-Schule", "Das Design von Philippe Starck schafft ein besonderes Ambiente", "Interessante Route zu den nahe gelegenen südlichen Buchten"],
    "sup-soller": ["Die kreisrunde Bucht ist ideal für absolute Anfänger", "Der Segelclub bietet Kurse und Ausrüstungsverleih", "Die historischen Züge die im Hafen ankommen sind ein Spektakel vom Wasser"],
    "sup-cala-major": ["Städtische Route entlang der Küste Palmas mit Blick auf Burg Bellver", "Club de Mar hat die beste Verleihbasis", "Gut kombinierbar mit einem Burgbesuch nach dem SUP"],
    "gtrentals-motorworld": ["Im Voraus buchen, besonders im Sommer", "Die Motorworld-Rennstrecke ist spektakulär zum Testen der Fahrzeuge", "Vollkaskoversicherung ist im Preis inbegriffen"],
    "rest-can-torrat": ["Spanferkel aus dem Holzofen probieren – die Spezialität des Hauses", "Bargeld mitbringen, Karten werden aber akzeptiert", "Der Hintergarten ist ideal für Sommerabende"],
    "rest-can-pedro-genova": ["Spanferkel und Pan amb oli sind unverzichtbar", "Das Lokal ist klein – in der Saison vorher reservieren", "Sehr gutes Preis-Leistungs-Verhältnis"],
    "rest-illeta-camp-de-mar": ["Restaurant liegt auf dem Wasser – Zugang über Holzsteg", "Reis und Meeresfrüchte sind die Spezialität", "Außentisch vorher reservieren"],
    "rest-sa-curva-hipodromo": ["Sonntags finden Pferderennen statt – ein einzigartiges Erlebnis", "Das Menü des Tages ist eines der besten Preis-Leistungs-Verhältnisse Palmas", "Hauptsächlich mittags geöffnet – Öffnungszeiten prüfen"],
    "rest-matias-son-ferriol": ["Typisches mallorquinisches Büfett mit saisonalen Produkten", "Sehr beliebt bei Einheimischen – Wochenenden vorher reservieren", "Hausgemachte Nachspeisen sind ein Highlight"],
    "rest-sa-ximbomba-genova": ["Jahrhundertelange Institution mit hervorragenden Kroketten und Tapas", "Der Hauswein ist überraschend gut", "Die Sommerterrasse ist sehr lebhaft"],
    "hike-port-des-canonge": ["Die Zufahrt mit dem Auto ist eine der malerischsten der Insel", "Die kleine lokale Bar serviert einfache Tapas und Getränke", "Nur wenige Touristen kommen hierher – Ruhe genießen"],
    "faro-ses-salines": ["Zufahrt über Schotterweg ab Colònia de Sant Jordi", "Die nahen Salinen sind ein Vogelparadies", "Sonnenuntergang vom Leuchtturm ist einer der schönsten der Insel"],
    "salt-des-freu": ["Technische Route die etwas Bergerfahrung erfordert", "Genug Wasser mitbringen – keine Quellen auf der Strecke", "Der Wasserfall ist nach Herbstregen besonders beeindruckend"],
    "sa-foradada": ["Der Weg von Son Marroig dauert ca. 30 Minuten bergab", "In Son Marroig um Erlaubnis für den privaten Weg bitten", "Der Steinkai ist ideal zum ins Wasser springen"],
    "mhares-sea-club-sunset": ["Sonnenuntergangs-Sessions beginnen um ca. 18 Uhr im Sommer", "Tage im Voraus reservieren – Plätze mit Meerblick sind begrenzt", "Begrüßungscocktail in vielen Paketen inbegriffen"],
    "calas-sur-llucmajor": ["Wenig bekannte Zone mit schwer zugänglichen unberührten Buchten", "Geländewagen erleichtert den Zugang, ist aber nicht zwingend", "Küstenpfad verbindet mehrere Buchten für eine Tageswanderung"],
    "calo-des-moro": ["Eines der ikonischsten Fotos Mallorcas – mit Warteschlange rechnen", "Im Sommer vor 8 Uhr ankommen um sie in Ruhe zu genießen", "Parkplatz liegt 15 Minuten zu Fuß entfernt"],
    "cala-agulla": ["Kostenloser Parkplatz liegt 1 km vom Strand entfernt", "Das Kiefernwäldchen dahinter ist ideal für ein Picknick", "Bei Levante-Wind können die Wellen etwas stärker sein"],
    "cala-mesquida": ["Großer Strand mit Platz auch in der Hochsaison", "Das Dünensystem hinter dem Strand ist geschützt", "Strandkioske von Juni bis September geöffnet"],
    "cala-llombards": ["Eine der elegantesten Buchten im Süden Mallorcas", "Der Klippen-Chiringuito ist ideal für den Aperitif", "Das smaragdgrüne Wasser ist außergewöhnlich fotogen"],
    "playa-de-muro": ["Teil des Naturparks s'Albufera – auf dem Weg Vögel beobachten", "Blaue-Flagge-Strand mit allen Einrichtungen", "Außerhalb der Saison kostenloser Parkplatz"],
    "cala-salmunia": ["Zufahrt über Privatweg – Grundstücke respektieren", "Das Wasser ist besonders ruhig, ideal für Kajak", "Eine der ruhigsten Buchten im Südosten"],
    "portals-vells-beach": ["Prähistorische in den Felsen gehauene Höhlen sind faszinierend", "FKK-Strand Es Bellu wenige Minuten entfernt", "Der Chiringuito serviert täglich frische Paella"],
    "cala-magraner": ["Nur zu Fuß erreichbar – 30 Minuten von der Straße", "Schnorchelausrüstung mitbringen – vielfältiger Meeresgrund", "Felsen bilden natürliche Pools ideal für Kinder"],
    "puig-de-randa": ["Drei Heiligtümer auf demselben Berg, jedes mit Geschichte", "Ramon Llull gründete das oberste Kloster im 13. Jahrhundert", "Einzigartiger Ausblick über die gesamte Zentralebene"],
    "son-marroig": ["Das alte Gut des Erzherzogs hat ein Museum mit persönlichen Erinnerungsstücken", "Vom Garten aus führt der Weg zu Sa Foradada", "Der Marmortempel von Carrara mit Meerblick ist sehr fotogen"],
    "mirador-na-burguesa": ["Per Mountainbike ab Palma erreichbar", "Am besten bei Sonnenaufgang wenn Palma erwacht", "Der Aufstiegsweg ist ab Son Rapinya gut ausgeschildert"],
    "talaia-albercutx": ["Einer der am wenigsten besuchten Gipfel am Cap de Formentor", "Der Pfad ab der Straße ist nicht ausgeschildert – Karte mitbringen", "Einzigartige Ausblicke auf das Kap und die Bucht von Pollença"],
    "puig-de-maria": ["Das Gipfelkloster bietet sehr einfache Pilgerzimmer an", "Aufstieg ab Pollença dauert ca. 45 Minuten", "Von der Spitze sind Bucht von Pollença und Bucht von Alcúdia gleichzeitig zu sehen"],
    "santuari-sant-salvador": ["Ganzjährig geöffnet mit Pilgerzimmern", "Das monumentale Kreuz und der Obelisk sind Ikonen des Inselinneren", "Von der Terrasse sind Ost- und Südküste der Insel zu sehen"],
    "mirador-coll-gramola": ["Idealer Halt auf der Strecke Andratx–Banyalbufar", "Eigener Parkplatz und Bänke zum Ausruhen", "Direkter Blick auf das Dorf Banyalbufar und seine Terrassenfelder"],
    "mercat-olivar": ["Der größte überdachte Markt Palmas, montags bis samstags geöffnet", "Im Obergeschoss gibt es Bars mit mallorquinischen Frühstücken", "Die Fischstände mit lokalem Fang sind für Meeresfrüchteliebhaber unverzichtbar"],
    "mercat-san-juan": ["Markt im alten Kloster Sant Felip Neri", "Samstags mit Handwerkermarkt von lokalen Erzeugern", "Erstklassige Restaurants in der Umgebung"],
    "mercat-pere-garau": ["Der authentischste und einheimischste Markt Palmas", "Mittwochs und samstags die größte Auswahl", "Günstigere Preise als auf den Touristenmärkten"],
    "mercat-artesanal-palma": ["Nur in der Tourismussaison von Frühling bis Herbst geöffnet", "Echtes mallorquinisches Kunsthandwerk – keine Importartikel", "Live-Handwerk-Vorführungen sehr interessant"],
    "mercat-gastronomic-sineu": ["Der bedeutendste Wochenmarkt des mallorquinischen Hinterlandes", "Morgens früh werden Nutztiere versteigert", "Käse und mallorquinische Wurstwaren sind unverzichtbar"],
    "ruta-cala-boquer": ["Start in Port de Pollença, einfache Busverbindung", "Die Bucht hat keinen Sand – Felsplatten, Matte mitbringen", "Rüppell-Geier nisten in den Klippenwänden des Tals"],
    "ruta-cala-murta": ["Rundwanderung ab Port de Pollença", "Der Pfad führt durch schattenreichen Waldbereich", "Die Bucht ist klein aber sehr geschützt – früh ankommen"],
    "ruta-cala-tuent": ["Abstieg vom Coll de Tuent ist sehr steil – Vorsicht", "Die Bucht ist wegen des schwierigen Zugangs ruhig", "Die Bar an der Bucht serviert sehr einfaches aber erfrischendes Essen"],
    "ruta-cala-varques": ["Beliebte Radtour ab Manacor oder Porto Cristo", "Der letzte Abschnitt ist Schotterweg und kann holprig sein", "Unter Wasser gibt es Höhlen die mit Schnorcheln zugänglich sind"],
    "ruta-cala-estreta": ["Eine der geheimnisvollsten Buchten an der Ostküste Mallorcas", "Der Zugangsweg erfordert gute Kondition", "Wasser und Schnorchel mitbringen – der Meeresgrund ist spektakulär"],
    "ruta-coll-baix": ["Der Strand Coll Baix gilt als einer der schönsten Mallorcas", "Letzter Abstieg über Felsgelände – festes Schuhwerk erforderlich", "Das türkisblaue Wasser ist das schönste Mallorcas"],
    "gem-cova-ses-bruixes": ["Nicht ausgeschildert – Offline-Karte vorher herunterladen", "Die Höhle ist klein, aber die Gesteinsformationen sind beeindruckend", "Natur respektieren – nichts hinterlassen"],
    "gem-font-de-la-vila": ["Die Quelle versorgt das Dorf seit Jahrhunderten mit Wasser", "Der Spaziergang ab Alaró dauert ca. 20 Minuten über gepflasterten Weg", "Nur wenige Menschen kommen hierher – Stille genießen"],
    "gem-bassa-de-can-coll": ["Der Stausee zieht im Winter Wasservögel an", "Das Gut ist Privatbesitz – nur öffentliche Zugänge nutzen", "Fernglas mitbringen für Vogelbeobachtung"],
    "gem-mirador-sa-trapa": ["Die Klosterruine Sa Trapa liegt auf dem Weg", "Bester Ausblick auf die Insel Sa Dragonera im Südwesten", "Der Aufstieg von Sant Elm dauert ca. 2 Stunden"],
    "cala-figuera-santanyi": ["Der Fischereihafen ist noch aktiv", "Morgens verkaufen Fischer ihren Fang direkt vom Boot", "Der Küstenrundweg hat wunderschöne Ausblicke"],
    "cala-santanyi": ["Der Kiosk serviert gute hausgemachte Eiscreme", "Die Felsformationen an den Enden des Strandes sind fotogen", "Organisierter Strand mit Liegestühlen und Sonnenschirmen"],
    "cala-millor": ["Breiter Sandstrand von fast 2 km Länge", "Ideal für Familien wegen des ruhigen Wassers", "Die Strandpromenade hat Restaurants für jeden Geschmack"],
    "port-de-soller-beach": ["Historische Straßenbahn kommt direkt zum Hafen", "Die Tramuntana-Berge im Hintergrund schaffen eine einzigartige Kulisse", "Der Segelclub organisiert Bootsausflüge bei Sonnenuntergang"],
    "cala-romantica": ["Ruhiges Wasser und feiner Sand – sehr beliebt bei Familien", "Das Kliff-Restaurant bietet spektakuläre Ausblicke", "Kostenloser Parkplatz in kurzer Entfernung"],
    "cala-barca-andratx": ["Versteckte Bucht zwischen Klippen, nur zu Fuß oder per Boot", "Außergewöhnlich klares, flaches Wasser ideal zum Schnorcheln", "Fischerboote des Hafens von Andratx nutzen sie als Zuflucht"],
    "playa-de-palma": ["Bus C1 aus dem Zentrum von Palma kommt direkt an den Strand", "Die Strandpromenade ist 8 km lang – ideal zum Laufen", "Balneario 6 ist der lebhafteste Abschnitt mit Bars und Musik"],
    "illetes": ["Einer der elegantesten Strände Mallorcas – Liegestühle online vorbuchen", "Restaurant Flanigan hat seit den 70ern Kultstatus", "Mit dem Katamaran-Fähre aus Palma ist die bequemste Anreise"],
    "cala-dor": ["Sportboothafen mit kosmopolitischem Flair", "Die umliegenden Buchten per Mietkajak erkunden", "Der Dienstags- und Donnerstagskünstlermarkt ist sehr beliebt"],
    "peguera": ["Feiner Sandstrand mit allen Einrichtungen", "Die zentrale Fußgängerzone hat ein breites Gastronomieangebot", "Tauch- und Wassersportläden in der kommerziellen Zone"],
    "playa-sant-elm": ["Direkter Blick auf die Insel Sa Dragonera – sehr fotogen", "Regelmäßige Fähre nach Sa Dragonera ab dem Hafen Sant Elm", "Das Dorf hat eine ruhige und authentische Atmosphäre"],
    "cala-llucalcari": ["Nur zu Fuß durch das malerische Dorf Llucalcari erreichbar", "Eine der intimsten und am wenigsten besuchten Buchten des Nordwestens", "Das Wasser neben den Felsen ist sehr tief – bei Kindern aufpassen"],
    "avenc-de-son-pou": ["Kostenloser Zugang aber Taschenlampe und festes Schuhwerk erforderlich", "Das Kalkstein-Schlot ist von unten spektakulär", "Gut kombinierbar mit einer Wanderung im umgebenden Wald"],
    "la-comuna-bunyola": ["Ausgedehntes Wegenetz – Karte des Consell de Mallorca herunterladen", "Ideal für Mountainbike – verschiedene Schwierigkeitsgrade", "Die Aussichtspunkte über die Zentralebene sind großartig"],
    "punta-negra-sant-vicenc": ["Dunkle Vulkanfelsen kontrastieren mit türkisfarbenem Wasser", "Außergewöhnliches Schnorcheln in Ritzen und kleinen Unterwasserhöhlen", "Per Kajak ab Cala Sant Vicenç für das beste Erlebnis anreisen"],
    "cavall-bernat-coves-blanques": ["Höhlen sind schwimmend oder per Kajak erreichbar", "Das Wasser in den Höhlen leuchtet intensiv blau", "Kajakfahrt ab Cala Sant Vicenç dauert ca. 30 Minuten"],
    "cueva-larga-azul-sant-vicenc": ["Höhle nur schwimmend erreichbar – gute körperliche Verfassung empfohlen", "Das blaue Licht in der Höhle ist am intensivsten am späten Vormittag", "Schnorchel und Flossen für mehr Komfort mitbringen"],
    "cala-en-basset": ["Der Wachturm aus dem 16. Jahrhundert dominiert den Eingang", "Zu Fuß von Sant Elm – ca. 30 Minuten Wanderung", "Das smaragdgrüne Wasser ist ideal zum Baden"],
    "cala-antena": ["Eine der ruhigsten Buchten im Osten Mallorcas", "Der Strandkiosk öffnet nur in der Hochsaison", "Posidonia auf dem Meeresgrund – Schnorcheln sehr empfehlenswert"],
    "cala-virgili": ["Zu Fuß ab Cala d'Or in ca. 20 Minuten erreichbar", "Nur wenige Meter breit – sehr intim", "Das hellgrüne klare Wasser ist besonders schön am Mittag"],
    "cala-marcal": ["Familienfreundlicher Strand mit Rettungsschwimmern in der Saison", "Wasserpedale zum Mieten bei Familien sehr beliebt", "Der nahe Campingplatz sorgt für gute Infrastruktur"],
    "ses-covetes": ["FKK-Strand Es Trenc nur wenige Gehminuten entfernt", "Der Es-Trenc-Kiosk liegt einen kurzen Spaziergang entfernt", "Die Dünenlandschaft dahinter ist sehr fotogen"],
    "es-carbo": ["Einer der wildesten und einsamsten Strände im Süden", "Keine Einrichtungen – alles Notwendige mitbringen", "Zufahrt über ca. 3 km Schotterweg"],
    "arenal-sa-rapita": ["Ruhiger Familienhafen mit entspannter Atmosphäre", "Das Restaurant des Nautikclubs serviert gute frische Meeresfrüchte", "Sehr ruhiges Wasser, ideal für kleine Kinder"],
    "cala-vinyes": ["Ruhiges Wasser ideal für Familien mit Kleinkindern", "Das Kliff-Restaurant bietet Ausblick auf das Eiland Es Malgrat", "Der Spaziergang von Santa Ponça dauert nur ca. 20 Minuten"],
    "cap-falco": ["Felsige Bucht am Ende eines Waldweges von Portals Vells", "Ausgezeichnetes Schnorcheln auf felsigem Meeresgrund", "Der Leuchtturm Cap Falcó ist der Orientierungspunkt"],
    "gorg-blau": ["Der Stausee ist umgeben von Tramuntana-Bergen", "Die Zufahrtstraße von Lluc ist spektakulär", "Der GR221-Fernwanderweg führt direkt am Stausee entlang"],
    "mhares-sea-club": ["Tisch auf der Terrasse für den Mittagsbereich im Voraus reservieren", "Zufahrt von Cala Figuera über steilen Weg", "An Wochentagen ruhiger als am Wochenende"],
    "mirador-des-colomer": ["Spektakuläre Aussicht auf den Felsen Colomer und die Bucht von Pollença", "Parkplatz kann im Sommer schnell voll sein – früh ankommen", "Mit guten Ferngläsern nistende Raubvögel sehen"],
}


def build_tips_with_fallback(tips_dict, place_id, original_tips):
    """Return translated tips, or empty list (which will fall back to English in the app)."""
    return tips_dict.get(place_id, [])


def main():
    with open(SEED, encoding="utf-8") as f:
        data = json.load(f)

    updated = 0
    for place in data["places"]:
        pid = place["id"]
        # Spanish tips
        place["tips_es"] = TIPS_ES.get(pid, [])
        # German
        place["name_de"] = NAME_DE.get(pid, "")
        place["description_de"] = DESC_DE.get(pid, "")
        place["tips_de"] = TIPS_DE.get(pid, [])
        # Russian / Chinese – empty for now (app falls back to English)
        place["name_ru"] = ""
        place["description_ru"] = ""
        place["tips_ru"] = []
        place["name_zh"] = ""
        place["description_zh"] = ""
        place["tips_zh"] = []
        updated += 1

    with open(SEED, "w", encoding="utf-8") as f:
        json.dump(data, f, ensure_ascii=False, indent=2)

    print(f"Updated {updated} places with localized fields.")
    # Quick sanity check
    sample_ids = ["es-trenc", "coves-drach", "seu-cathedral"]
    for pid in sample_ids:
        p = next(x for x in data["places"] if x["id"] == pid)
        print(f"\n{pid}:")
        print(f"  name_de = {p['name_de']}")
        print(f"  tips_es = {p['tips_es'][:1]}")
        print(f"  tips_de = {p['tips_de'][:1]}")


if __name__ == "__main__":
    main()
